/* Generated by Yosys 0.37+27 (git sha1 ebf6128d9, clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* top =  1  *)
(* src = "fsm_hot.v:1.1-237.10" *)
module vdf_2_fsm(clk, rst, in, out);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  (* src = "fsm_hot.v:2.16-2.19" *)
  input clk;
  wire clk;
  (* src = "fsm_hot.v:4.22-4.24" *)
  input [1:0] in;
  wire [1:0] in;
  (* src = "fsm_hot.v:10.11-10.20" *)
  wire [7:0] new_state;
  (* src = "fsm_hot.v:5.23-5.26" *)
  output [1:0] out;
  wire [1:0] out;
  (* src = "fsm_hot.v:9.11-9.16" *)
  wire [1:0] outer;
  (* src = "fsm_hot.v:8.11-8.17" *)
  wire [1:0] outery;
  (* src = "fsm_hot.v:3.16-3.19" *)
  input rst;
  wire rst;
  (* src = "fsm_hot.v:7.11-7.16" *)
  wire [7:0] state;
  INV_X1 _073_ (
    .A(state[0]),
    .ZN(_010_)
  );
  INV_X1 _074_ (
    .A(state[1]),
    .ZN(_011_)
  );
  INV_X1 _075_ (
    .A(state[2]),
    .ZN(_012_)
  );
  INV_X1 _076_ (
    .A(state[3]),
    .ZN(_013_)
  );
  INV_X1 _077_ (
    .A(state[4]),
    .ZN(_014_)
  );
  INV_X1 _078_ (
    .A(state[6]),
    .ZN(_015_)
  );
  INV_X1 _079_ (
    .A(state[7]),
    .ZN(_016_)
  );
  INV_X1 _080_ (
    .A(in[1]),
    .ZN(_017_)
  );
  INV_X1 _081_ (
    .A(rst),
    .ZN(_000_)
  );
  NOR2_X1 _082_ (
    .A1(state[6]),
    .A2(state[7]),
    .ZN(_018_)
  );
  NOR2_X1 _083_ (
    .A1(state[5]),
    .A2(state[4]),
    .ZN(_019_)
  );
  NOR3_X1 _084_ (
    .A1(state[5]),
    .A2(state[6]),
    .A3(state[7]),
    .ZN(_020_)
  );
  NOR4_X1 _085_ (
    .A1(state[5]),
    .A2(state[4]),
    .A3(state[6]),
    .A4(state[7]),
    .ZN(_021_)
  );
  NOR2_X1 _086_ (
    .A1(state[0]),
    .A2(state[1]),
    .ZN(_022_)
  );
  AND4_X1 _087_ (
    .A1(state[2]),
    .A2(_013_),
    .A3(_021_),
    .A4(_022_),
    .ZN(_023_)
  );
  NAND4_X1 _088_ (
    .A1(state[2]),
    .A2(_013_),
    .A3(_021_),
    .A4(_022_),
    .ZN(_024_)
  );
  NOR2_X1 _089_ (
    .A1(state[2]),
    .A2(state[3]),
    .ZN(_025_)
  );
  NOR4_X1 _090_ (
    .A1(state[0]),
    .A2(state[1]),
    .A3(state[2]),
    .A4(state[3]),
    .ZN(_026_)
  );
  AND4_X1 _091_ (
    .A1(state[5]),
    .A2(_014_),
    .A3(_018_),
    .A4(_026_),
    .ZN(_027_)
  );
  INV_X1 _092_ (
    .A(_027_),
    .ZN(_028_)
  );
  AND3_X1 _093_ (
    .A1(state[4]),
    .A2(_020_),
    .A3(_026_),
    .ZN(_029_)
  );
  NAND3_X1 _094_ (
    .A1(state[4]),
    .A2(_020_),
    .A3(_026_),
    .ZN(_030_)
  );
  NOR2_X1 _095_ (
    .A1(_027_),
    .A2(_029_),
    .ZN(_031_)
  );
  NOR3_X1 _096_ (
    .A1(_023_),
    .A2(_027_),
    .A3(_029_),
    .ZN(_032_)
  );
  AND4_X1 _097_ (
    .A1(state[0]),
    .A2(_011_),
    .A3(_021_),
    .A4(_025_),
    .ZN(_033_)
  );
  NAND4_X1 _098_ (
    .A1(state[0]),
    .A2(_011_),
    .A3(_021_),
    .A4(_025_),
    .ZN(_034_)
  );
  NAND4_X1 _099_ (
    .A1(_010_),
    .A2(state[1]),
    .A3(_021_),
    .A4(_025_),
    .ZN(_035_)
  );
  AND2_X1 _100_ (
    .A1(_034_),
    .A2(_035_),
    .ZN(_036_)
  );
  NAND4_X1 _101_ (
    .A1(state[6]),
    .A2(_016_),
    .A3(_019_),
    .A4(_026_),
    .ZN(_037_)
  );
  INV_X1 _102_ (
    .A(_037_),
    .ZN(_038_)
  );
  AND4_X1 _103_ (
    .A1(_015_),
    .A2(state[7]),
    .A3(_019_),
    .A4(_026_),
    .ZN(_039_)
  );
  AND4_X1 _104_ (
    .A1(_012_),
    .A2(state[3]),
    .A3(_021_),
    .A4(_022_),
    .ZN(_040_)
  );
  NOR2_X1 _105_ (
    .A1(_039_),
    .A2(_040_),
    .ZN(_041_)
  );
  NAND4_X1 _106_ (
    .A1(_032_),
    .A2(_036_),
    .A3(_037_),
    .A4(_041_),
    .ZN(_042_)
  );
  NAND2_X1 _107_ (
    .A1(_017_),
    .A2(in[0]),
    .ZN(_043_)
  );
  NOR2_X1 _108_ (
    .A1(in[1]),
    .A2(in[0]),
    .ZN(_044_)
  );
  OR2_X1 _109_ (
    .A1(in[1]),
    .A2(in[0]),
    .ZN(_045_)
  );
  OAI221_X1 _110_ (
    .A(_042_),
    .B1(_043_),
    .B2(_028_),
    .C1(_045_),
    .C2(_036_),
    .ZN(new_state[0])
  );
  NOR2_X1 _111_ (
    .A1(_017_),
    .A2(in[0]),
    .ZN(_046_)
  );
  INV_X1 _112_ (
    .A(_046_),
    .ZN(_047_)
  );
  OAI22_X1 _113_ (
    .A1(_034_),
    .A2(_043_),
    .B1(_047_),
    .B2(_035_),
    .ZN(new_state[1])
  );
  NAND2_X1 _114_ (
    .A1(in[1]),
    .A2(in[0]),
    .ZN(_048_)
  );
  AOI22_X1 _115_ (
    .A1(_040_),
    .A2(_044_),
    .B1(_046_),
    .B2(_023_),
    .ZN(_049_)
  );
  OAI221_X1 _116_ (
    .A(_049_),
    .B1(_043_),
    .B2(_035_),
    .C1(_034_),
    .C2(_048_),
    .ZN(new_state[2])
  );
  NOR2_X1 _117_ (
    .A1(_023_),
    .A2(_040_),
    .ZN(_050_)
  );
  AOI21_X1 _118_ (
    .A(_048_),
    .B1(_050_),
    .B2(_035_),
    .ZN(new_state[3])
  );
  AOI21_X1 _119_ (
    .A(_043_),
    .B1(_050_),
    .B2(_037_),
    .ZN(new_state[4])
  );
  NAND2_X1 _120_ (
    .A1(_033_),
    .A2(_046_),
    .ZN(_051_)
  );
  OAI21_X1 _121_ (
    .A(_051_),
    .B1(_045_),
    .B2(_032_),
    .ZN(new_state[5])
  );
  AND2_X1 _122_ (
    .A1(_039_),
    .A2(_044_),
    .ZN(_052_)
  );
  XNOR2_X1 _123_ (
    .A(in[1]),
    .B(in[0]),
    .ZN(_053_)
  );
  AOI21_X1 _124_ (
    .A(_052_),
    .B1(_053_),
    .B2(_038_),
    .ZN(_054_)
  );
  NAND2_X1 _125_ (
    .A1(_040_),
    .A2(_046_),
    .ZN(_055_)
  );
  OAI211_X1 _126_ (
    .A(_054_),
    .B(_055_),
    .C1(_030_),
    .C2(_048_),
    .ZN(new_state[6])
  );
  NOR2_X1 _127_ (
    .A1(in[0]),
    .A2(_037_),
    .ZN(_056_)
  );
  OAI21_X1 _128_ (
    .A(_045_),
    .B1(_056_),
    .B2(_039_),
    .ZN(_057_)
  );
  OAI221_X1 _129_ (
    .A(_057_),
    .B1(_053_),
    .B2(_030_),
    .C1(_017_),
    .C2(_028_),
    .ZN(new_state[7])
  );
  AOI22_X1 _130_ (
    .A1(in[1]),
    .A2(_027_),
    .B1(_033_),
    .B2(_048_),
    .ZN(_058_)
  );
  AOI21_X1 _131_ (
    .A(in[1]),
    .B1(_024_),
    .B2(_035_),
    .ZN(_059_)
  );
  OAI221_X1 _132_ (
    .A(_058_),
    .B1(_046_),
    .B2(_037_),
    .C1(in[0]),
    .C2(_031_),
    .ZN(_060_)
  );
  OR4_X1 _133_ (
    .A1(_040_),
    .A2(_052_),
    .A3(_059_),
    .A4(_060_),
    .ZN(outer[0])
  );
  AOI222_X1 _134_ (
    .A1(in[0]),
    .A2(_038_),
    .B1(_040_),
    .B2(_043_),
    .C1(_053_),
    .C2(_039_),
    .ZN(_061_)
  );
  OAI21_X1 _135_ (
    .A(in[1]),
    .B1(_027_),
    .B2(_029_),
    .ZN(_062_)
  );
  NAND4_X1 _136_ (
    .A1(_035_),
    .A2(_051_),
    .A3(_061_),
    .A4(_062_),
    .ZN(outer[1])
  );
  INV_X1 _137_ (
    .A(rst),
    .ZN(_001_)
  );
  INV_X1 _138_ (
    .A(rst),
    .ZN(_002_)
  );
  INV_X1 _139_ (
    .A(rst),
    .ZN(_003_)
  );
  INV_X1 _140_ (
    .A(rst),
    .ZN(_004_)
  );
  INV_X1 _141_ (
    .A(rst),
    .ZN(_005_)
  );
  INV_X1 _142_ (
    .A(rst),
    .ZN(_006_)
  );
  INV_X1 _143_ (
    .A(rst),
    .ZN(_007_)
  );
  INV_X1 _144_ (
    .A(rst),
    .ZN(_008_)
  );
  INV_X1 _145_ (
    .A(rst),
    .ZN(_009_)
  );
  (* src = "fsm_hot.v:13.1-25.8" *)
  DFFS_X1 _146_ (
    .CK(clk),
    .D(new_state[0]),
    .Q(state[0]),
    .QN(_072_),
    .SN(_000_)
  );
  (* src = "fsm_hot.v:13.1-25.8" *)
  DFFR_X1 _147_ (
    .CK(clk),
    .D(new_state[1]),
    .Q(state[1]),
    .QN(_071_),
    .RN(_001_)
  );
  (* src = "fsm_hot.v:13.1-25.8" *)
  DFFR_X1 _148_ (
    .CK(clk),
    .D(new_state[2]),
    .Q(state[2]),
    .QN(_070_),
    .RN(_002_)
  );
  (* src = "fsm_hot.v:13.1-25.8" *)
  DFFR_X1 _149_ (
    .CK(clk),
    .D(new_state[3]),
    .Q(state[3]),
    .QN(_069_),
    .RN(_003_)
  );
  (* src = "fsm_hot.v:13.1-25.8" *)
  DFFR_X1 _150_ (
    .CK(clk),
    .D(new_state[4]),
    .Q(state[4]),
    .QN(_068_),
    .RN(_004_)
  );
  (* src = "fsm_hot.v:13.1-25.8" *)
  DFFR_X1 _151_ (
    .CK(clk),
    .D(new_state[5]),
    .Q(state[5]),
    .QN(_067_),
    .RN(_005_)
  );
  (* src = "fsm_hot.v:13.1-25.8" *)
  DFFR_X1 _152_ (
    .CK(clk),
    .D(new_state[6]),
    .Q(state[6]),
    .QN(_066_),
    .RN(_006_)
  );
  (* src = "fsm_hot.v:13.1-25.8" *)
  DFFR_X1 _153_ (
    .CK(clk),
    .D(new_state[7]),
    .Q(state[7]),
    .QN(_065_),
    .RN(_007_)
  );
  (* src = "fsm_hot.v:13.1-25.8" *)
  DFFR_X1 _154_ (
    .CK(clk),
    .D(outer[0]),
    .Q(outery[0]),
    .QN(_064_),
    .RN(_008_)
  );
  (* src = "fsm_hot.v:13.1-25.8" *)
  DFFR_X1 _155_ (
    .CK(clk),
    .D(outer[1]),
    .Q(outery[1]),
    .QN(_063_),
    .RN(_009_)
  );
  assign out = outery;
endmodule
